/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum DiagnosticLevel {
  Error = 0,
  Warning = 1
}
export function run(code: string): void
export type JsComponentCompiler = ComponentCompiler
export class ComponentCompiler {
  constructor()
  setIncludePaths(includePaths: Array<string>): void
  includePaths(): Array<string>
  setStyle(style: string): void
  style(): string | null
  diagnostics(): Array<JsDiagnostic>
  buildFromPath(path: string): JsComponentDefinition | null
  buildFromSource(sourceCode: string, path: string): JsComponentDefinition | null
}
export type JsComponentDefinition = ComponentDefinition
export class ComponentDefinition {
  constructor()
  name(): string
}
export type JsDiagnostic = Diagnostic
export class Diagnostic { }
