/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function run(code: string): void
export type JsComponentCompiler = ComponentCompiler
export class ComponentCompiler {
  constructor()
  setIncludePaths(includePaths: Array<string>): void
  includePaths(): Array<string>
  setStyle(style: string): void
  style(): string | null
}
