/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum DiagnosticLevel {
  Error = 0,
  Warning = 1
}
export function run(code: string): void
export type JsComponentCompiler = ComponentCompiler
export class ComponentCompiler {
  constructor()
  set includePaths(includePaths: Array<string>)
  get includePaths(): Array<string>
  set style(style: string)
  get style(): string | null
  get diagnostics(): Array<JsDiagnostic>
  buildFromPath(path: string): JsComponentDefinition | null
  buildFromSource(sourceCode: string, path: string): JsComponentDefinition | null
}
export type JsComponentDefinition = ComponentDefinition
export class ComponentDefinition {
  constructor()
  get name(): string
  create(): JsComponentInstance | null
}
export class JsComponentInstance {
  constructor()
  run(): void
}
export type JsDiagnostic = Diagnostic
export class Diagnostic { }
